### PR TITLE
Teletan matched string with [characters]{7} and thus also matched 8 c…

### PR DESCRIPTION
**Pull request by theodiefenthal**
…har strings. It also used a strange character definition syntax with M-N-P-Z form, which would allow - char as well.

Generator was also a bit inefficient and was replaced by a simpler version.

### CODE REVIEW

**Comment by kreincke** [comment]
Many thanks for your helpful work. Some of your proposals seem to be very elegant. The team will manage your work on Monday. BTW: Why did you expand in your regex the range notation in the original by a complete list? Is there anything wrong with the range notation 0-9 etc. ?

**Comment by theodiefenthal** [comment]
Hi @kreincke , I expanded to a list just that it's easier to generate TANs with a simple random number generator. There are libraries to generate random strings given a regex, but I didn't want to include an additional dependency to your project. 
Further, I found the list of characters easier to be read than the regex pattern with too many skipped characters in the set.

**Comment by kreincke** [comment]
HI @theodiefenthal Many thanks for this excellent explanation.

**Comment by theodiefenthal** [comment]
Oh dear, I just realized that I replaced generateTan instead of generateTeletan. Too much tan confusion at 2am :) 

@dfischer-tech thankfully fixes this already in https://github.com/corona-warn-app/cwa-verification-server/pull/51 , so I won't add another commit+PR+proper unit test for valid tan and teletan here anymore.

**Pull request merged**
